# Generated by Django 5.2.8 on 2025-11-27 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='businesses.business')),
                ('service', models.ForeignKey(blank=True, help_text='Optional: working hours specific to a service', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='services.service')),
            ],
            options={
                'ordering': ['business', 'weekday', 'start_time'],
                'unique_together': {('business', 'service', 'weekday')},
            },
        ),
    ]
